package com.company.humanResources.user;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import com.company.IdGenerator;

public class User {
	private static IdGenerator idGenerator = new IdGenerator("USER");

	private String fullName;
	private String email;
	private String password;
	private String paymentMethod;
	private String passportSerial;
	private String phoneNumber;
	private String userId;
	private boolean isLoggedIn;

	public User(String fullName, String password, String email, String paymentMethod, String passportSerial, String phoneNumber) {
		this.fullName = fullName;
		this.passportSerial = passportSerial;
		this.password = password;
		this.email = email;
		this.paymentMethod = paymentMethod;
		this.phoneNumber = phoneNumber;
		this.userId = idGenerator.generateId();
	}
	
	public boolean coincides(String passportSerial, String phoneNumber, String paymentMethod, String email) {
		return this.paymentMethod.equals(paymentMethod)
				|| this.passportSerial.equals(passportSerial)
				|| this.phoneNumber.equals(phoneNumber)
				|| this.email.equals(email);
	}
	
	public boolean canAuth(String email, String password) {
		return this.email.equals(email)
				&& this.password.equals(password);
	}
	
	public void setIsLoggedIn(boolean isLoggedIn) {
		this.isLoggedIn = isLoggedIn;
	}
	
	public String getUserId() {
		return userId;
	}
	
	public boolean getIsLoggedIn() {
		return isLoggedIn;
	}
}
