package com.company.lock;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import com.company.IdGenerator;

public class Lock {
	private static final IdGenerator idGenetator = new IdGenerator("LOCK");

	private String lockId;
	private String targetId;
	private String targetType;

	public Lock(String targetId, String targetType) {
		this.targetId = targetId;
		this.targetType = targetType;
		this.lockId = idGenetator.generateId();
	}

	public void unlock() {
		System.out.println("LOCK N" + lockId + " UNLOCKED");
	}
	
	public void lock() {
		System.out.println("LOCK N" + lockId + " LOCKED");
	}
	
	public boolean matches(String lockId, String targetId, String targetType) {
		return this.lockId.equals(lockId)
				&& this.targetId.equals(targetId)
				&& this.targetType.equals(targetType);
	}
	
	public boolean matches(String lockId) {
		return this.lockId.equals(lockId);
	}

	public String getTargetId() {
		return targetId;
	}
}
