package com.company.lock;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import com.company.gps.Location;

import java.util.ArrayList;
import java.util.List;

public class SecuritySystemController {
	private List<Lock> locks;

	public SecuritySystemController() {
		locks = new ArrayList<>();
	}

	public void findAndUnlock(String lockId, String targetId, String targetType) {
		for (Lock lock : locks) {
			if (lock.matches(lockId, targetId, targetType)) {
				lock.unlock();
				return;
			}
		}
	}
	
	public void findAndLock(String lockId) {
		for (Lock lock : locks) {
			if (lock.matches(lockId)) {
				lock.lock();
				return;
			}
		}
	}
	
	public String getTarget(String lockId) {
		for (Lock lock : locks) {
			if (lock.matches(lockId)) {
				return lock.getTargetId();
			}
		}

		return null;
	}

	public void addLock(Lock lock) {
		locks.add(lock);
	}
}
