package com.company.lock;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import com.company.gps.Location;
import com.company.transaction.Token;

import java.util.ArrayList;
import java.util.List;

public class SecuritySystemController {
	private List<Lock> locks;

	public SecuritySystemController() {
		locks = new ArrayList<>();

		Lock firstVehicleLock = new Lock("VEHICLE_1", Token.TARGET_TYPE_VEHICLE);
		Lock secondVehicleLock = new Lock("VEHICLE_2", Token.TARGET_TYPE_VEHICLE);
		Lock thirthVehicleLock = new Lock("VEHICLE_3", Token.TARGET_TYPE_VEHICLE);
		Lock firstMainGate = new Lock("PARKING_1", Token.TARGET_TYPE_MAIN_GATE);
		Lock secondMainGate = new Lock("PARKING_2", Token.TARGET_TYPE_MAIN_GATE);
		Lock firstSecondGate = new Lock("PARKING_1", Token.TARGET_TYPE_SECOND_GATE);
		Lock secondSecondGate = new Lock("PARKING_2", Token.TARGET_TYPE_SECOND_GATE);

		locks.add(firstVehicleLock);
		locks.add(secondVehicleLock);
		locks.add(thirthVehicleLock);
		locks.add(firstMainGate);
		locks.add(secondMainGate);
		locks.add(firstSecondGate);
		locks.add(secondSecondGate);
	}

	public boolean findAndUnlock(String lockId, String targetId, String targetType) {
		for (Lock lock : locks) {
			if (lock.matches(lockId, targetId, targetType)) {
				lock.unlock();
				return true;
			}
		}

		return false;
	}
	
	public void findAndLock(String lockId) {
		for (Lock lock : locks) {
			if (lock.matches(lockId)) {
				lock.lock();
				return;
			}
		}
	}
	
	public String getTarget(String lockId) {
		for (Lock lock : locks) {
			if (lock.matches(lockId)) {
				return lock.getTargetId();
			}
		}

		return null;
	}
}
