package com.company.humanResources;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import com.company.gps.Location;
import com.company.humanResources.crew.Crew;
import com.company.humanResources.user.User;
import com.company.humanResources.user.UserCatalog;

public class HumanResourceController {
	private UserCatalog userCatalog;
	private Crew crew;

	public HumanResourceController() {
		userCatalog = new UserCatalog();
		crew = new Crew();
	}

	public boolean registerUser(String fullName, String password, String email, String paymentMethod, String passportSerial, String phoneNumber) {
		return userCatalog.register(fullName, password, email, paymentMethod, passportSerial, phoneNumber);
	}
	
	public String loginUser(String email, String password) {
		User user = userCatalog.findUser(email, password);

		if (user == null) {
			return null;
		}

		user.setIsLoggedIn(true);

		return user.getUserId();
	}
	
	public boolean isUserLoggedIn(String userId) {
		return userCatalog.isUserLoggedIn(userId);
	}
	
	public String findUserId(String email, String password) {
		User user = userCatalog.findUser(email, password);

		return user.getUserId();
	}

	public String findUserEmail(String userId) {
		User user = userCatalog.findUser(userId);

		return user.getEmail();
	}
	
	public void notifySupportCrew(String parkingId, String vehicleId, String lockId) {
		crew.notifySupportCrew(parkingId, "Move " + vehicleId + " to " + lockId);
	}
	
	public void notifySecurityCrew(Location location, String vehicleId, String parkingId) {
		crew.notifySecurityCrew(location, "At location " + location + " vehicle " + vehicleId + " deliver to " + parkingId);
	}
}