package com.company.property.parking;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import com.company.IdGenerator;

public class Parking {
	private static IdGenerator idGenerator = new IdGenerator("PARKING");

	private String parkingId;
	private String address;
	private String name;

	public Parking(String address, String name) {
		this.address = address;
		this.name = name;
		this.parkingId = idGenerator.generateId();
	}

	public String getParkingId() {
		return parkingId;
	}

	@Override
	public String toString() {
		return "ID : " + parkingId + "\n"
				+ "ADDRESS : " + address + "\n"
				+ "NAME : " + name + "\n";
	}
}
