//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//

package com.company;

import com.company.TickerObserver;

import java.util.List;

public class DailyTicker {
	private List<TickerObserver> observers;

	public void attach(Object observer) {
	
	}
	
	public void tick() {
	
	}
	
	public void notify(Object date) {
	
	}
}
