package com.company.gps;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//




public class GPSDevice {
	private String gpsDeviceId;
	private String vehicleId;
	private Location location;

	public GPSDevice(String gpsDeviceId, String vehicleId, Location location) {
		this.gpsDeviceId = gpsDeviceId;
		this.vehicleId = vehicleId;
		this.location = location;
	}

	public String getVehicleId() {
		return vehicleId;
	}

	public String getGpsDeviceId() {
		return gpsDeviceId;
	}
	
	public Location getLocation() {
		return location;
	}
}
