package com.company.gps;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//




public class GPSTrackerController {
	private GPSDevice devices;
	public void getLocation(Object vehicleId) {
	
	}
}
