package com.company.gps;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import java.util.ArrayList;
import java.util.List;

public class GPSTrackerController {
	private List<GPSDevice> devices;

	public GPSTrackerController() {
		this.devices = new ArrayList<>();

		GPSDevice device = new GPSDevice("VEHICLE_2", new Location(0.5f, 0.5f));
		devices.add(device);
	}

	public Location getLocation(String vehicleId) {
		for (GPSDevice device : devices) {
			if (device.getVehicleId().equals(vehicleId)) {
				return device.getLocation();
			}
		}

		return null;
	}
}
