package com.company.property;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import com.company.property.parking.Parking;
import com.company.property.parking.ParkingCatalog;
import com.company.property.vehicle.*;

import java.util.List;

public class PropertyController {
	private ParkingCatalog parkingCatalog;
	private VehicleCatalog vehicleCatalog;

	public PropertyController() {
		parkingCatalog = new ParkingCatalog();
		vehicleCatalog = new VehicleCatalog();

		// Initialize parking catalog
		Parking centerParking = new Parking("Avobyan 13", "Central Parking");
		Parking qanaqerParking = new Parking("Zaryan 26", "Qanaqer Parking");

		parkingCatalog.addParking(centerParking);
		parkingCatalog.addParking(qanaqerParking);

		// Initialize vehicle catalog
		Van van = new Van(1000, 2, 2);
		VehicleDescription vanDescription = new VanAdapter("Subaru", 3000, van);
		Vehicle vanVehicle = new Vehicle("GPS_1", "A1", "PARKING_1", vanDescription);
		Car car = new Car(4, 350);
		VehicleDescription carDescription = new CarAdapter("Subaru", 2500, car);
		Vehicle carVehicle = new Vehicle("GPS_2", "A2", "PARKING_1", carDescription);
		MotorBike motorBike = new MotorBike(true, 2, 50);
		VehicleDescription motorBikeDescription = new MotorBikeAdapter("Subaru", 2000, motorBike);
		Vehicle motorBikeVehicle = new Vehicle("GPS_3", "A3", "PARKING_1", motorBikeDescription);

		vehicleCatalog.addVehicle(vanVehicle);
		vehicleCatalog.addVehicle(carVehicle);
		vehicleCatalog.addVehicle(motorBikeVehicle);
	}

	public List<Parking> getParkings() {
		return parkingCatalog.getParkings();
	}
	
	public boolean doVehicleExists(String vehicleId, String parkingId) {
		return vehicleCatalog.doVehicleExists(vehicleId, parkingId);
	}

	public List<Vehicle> searchInParking(String producer, String parkingId, int minPrice, int maxPrice, int seats, float minVolume, float maxVolume) {
		return vehicleCatalog.searchInParking(producer, parkingId, minPrice, maxPrice, seats, minVolume, maxVolume);
	}
}
