package com.company.humanResources.crew;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import com.company.gps.Location;

public class AlarmCrewMember extends CrewMember {
	private Location[] authoritySegment = new Location[4];

	public AlarmCrewMember(String memberName, String memberPhone, String memberEmail, String memberId, Location[] authoritySegment) {
		super(memberName, memberPhone, memberEmail, memberId);

		this.authoritySegment = authoritySegment;
	}

	@Override
	public void notify(String message) {
		System.out.print("SECURITY NOTIFIED " + message);
	}
	
	public boolean isInSegment(Location location) {
		return location.getLatitude() >= authoritySegment[0].getLatitude() && location.getLongitude() >= authoritySegment[0].getLongitude()
				&& location.getLatitude() >= authoritySegment[1].getLatitude() && location.getLongitude() <= authoritySegment[1].getLongitude()
				&& location.getLatitude() <= authoritySegment[2].getLatitude() && location.getLongitude() <= authoritySegment[2].getLongitude()
				&& location.getLatitude() <= authoritySegment[3].getLatitude() && location.getLongitude() >= authoritySegment[3].getLongitude();
	}
}
