package com.company.humanResources.crew;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import com.company.gps.Location;

import java.util.ArrayList;
import java.util.List;

public class Crew {
	private List<AlarmCrewMember> securityCrew;
	private List<SupportCrewMember> supportCrew;

	public Crew() {
		this.securityCrew = new ArrayList<AlarmCrewMember>();
		this.supportCrew = new ArrayList<SupportCrewMember>();
	}

	public void addSupportMember(SupportCrewMember supportCrewMember) {
		supportCrew.add(supportCrewMember);
	}

	public void addSecurityMember(AlarmCrewMember alarmCrewMember) {
		securityCrew.add(alarmCrewMember);
	}

	public void notifySupportCrew(String parkingId, String message) {
		for(SupportCrewMember support: supportCrew) {

			if (support.getParkingId() == parkingId)
				support.notify(message);
		}
	}
	
	public void notifySecurityCrew(Location location, String message) {

		for(AlarmCrewMember crewMember: securityCrew){

			if(crewMember.isInSegment(location))
				crewMember.notify(message);

		}

		}
	}

