package com.company.humanResources.crew;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import com.company.gps.Location;

import java.util.ArrayList;
import java.util.List;

public class Crew {
	private List<SecurityCrewMember> securityCrew;
	private List<SupportCrewMember> supportCrew;

	public Crew() {
		this.securityCrew = new ArrayList<>();
		this.supportCrew = new ArrayList<>();

		SupportCrewMember supportMember = new SupportCrewMember("Marsel", "333990099", "marsel@yahoo.com", "PARKING_1");
		addSupportMember(supportMember);

		SecurityCrewMember alarmCrewMember = new SecurityCrewMember("Bond, James Bond", "007", "james@bond.m7", new Location[] {
				new Location(0.0f, 0.0f),
				new Location(0.0f, 1.0f),
				new Location(1.0f, 1.0f),
				new Location(1.0f, 0.0f)
		});
		addSecurityMember(alarmCrewMember);
	}

	public void addSupportMember(SupportCrewMember supportCrewMember) {
		supportCrew.add(supportCrewMember);
	}

	public void addSecurityMember(SecurityCrewMember alarmCrewMember) {
		securityCrew.add(alarmCrewMember);
	}

	public void notifySupportCrew(String parkingId, String message) {
		for(SupportCrewMember support : supportCrew) {
			if (support.getParkingId().equals(parkingId)) {
				support.notify(message);
			}
		}
	}
	
	public void notifySecurityCrew(Location location, String message) {
		for(SecurityCrewMember crewMember : securityCrew) {
			if (crewMember.isInSegment(location)) {
				crewMember.notify(message);
			}
		}
	}
}

