package com.company.humanResources.crew;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import java.util.ArrayList;
import java.util.List;

public class Crew {
	private List<AlarmCrewMember> securityCrew;
	private List<SupportCrewMember> supportCrew;

	public Crew() {
		this.securityCrew = new ArrayList<>();
		this.supportCrew = new ArrayList<>();
	}

	public void addSupportMember(SupportCrewMember supportCrewMember) {
		supportCrew.add(supportCrewMember);
	}

	public void addSecurityMember(AlarmCrewMember alarmCrewMember) {
		securityCrew.add(alarmCrewMember);
	}

	public void notifySupportCrew(String parkingId, String message) {

	}
	
	public void notifySecurityCrew(String  location, String message) {
	
	}
}
