//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//

package com.company.property.vehicle;

public class Car {
	private int beltNumber;
	private float maxLuggageVolume;

	public Car(int beltNumber, float maxLuggageVolume) {
		this.beltNumber = beltNumber;
		this.maxLuggageVolume = maxLuggageVolume;
	}

	public int getBeltNumber() {
		return beltNumber;
	}
	
	public float getMaxLuggageVolume() {
		return maxLuggageVolume;
	}

	@Override
	public String toString() {
		return "BELTS NUMBER : " + beltNumber + "\n"
				+ "LUGGAGE VOLUME : " + maxLuggageVolume + "\n";
	}

}
