//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//

package com.company.property.vehicle;

public class CarAdapter extends VehicleDescription {
	private Car car;

	public CarAdapter(String producer, int price, Car car) {
		super(producer, price);

		this.car = car;
	}

	@Override
	public int getSeatNumber() {
		return car.getBeltNumber();
	}

	@Override
	public float getMaxVolume() {
		return car.getMaxLuggageVolume();
	}

	@Override
	public String toString() {
		return super.toString() + car.toString();
	}
}
