package com.company.property.vehicle;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//




public class Van {
	private float maxVolume;
	private int frontPlaces;
	private int backPlaces;

	public Van(float maxVolume, int frontPlaces, int backPlaces) {
		this.maxVolume = maxVolume;
		this.frontPlaces = frontPlaces;
		this.backPlaces = backPlaces;
	}

	public float getMaxVolume() {
		return maxVolume;
	}
	
	public int getFrontPlaces() {
		return frontPlaces;
	}
	
	public int getBackPlaces() {
		return backPlaces;
	}

	@Override
	public String toString() {
		return "VOLUME : " + maxVolume + "\n"
				+ "FRONT SEATS : " + frontPlaces + "\n"
				+ "BACK SEATS : " + backPlaces + "\n";
	}
}
