package com.company.property.vehicle;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


public class VanAdapter extends VehicleDescription {
	private Van van;

	public VanAdapter(String producer, int price, Van van) {
		super(producer, price);

		this.van = van;
	}

	@Override
	public int getSeatNumber() {
		return van.getFrontPlaces() + van.getBackPlaces();
	}

	@Override
	public float getMaxVolume() {
		return van.getMaxVolume();
	}

	@Override
	public String toString() {
		return super.toString() + van.toString();
	}
}
