//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Vehicle Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


package com.company.property.vehicle;

import java.util.ArrayList;
import java.util.List;

public class VehicleCatalog {
	private List<Vehicle> vehicles;

	public VehicleCatalog() {
		this.vehicles = new ArrayList<>();
	}

	public List<Vehicle> searchInParking(String producer, String parkingId, int minPrice, int maxPrice, int seats, float minVolume, float maxVolume) {
		List<Vehicle> foundVehicles = new ArrayList<>();

		for (Vehicle vehicle : vehicles) {
			if (vehicle.matches(producer, parkingId, minPrice, maxPrice, seats, minVolume, maxVolume)) {
				foundVehicles.add(vehicle);
			}
		}

		return foundVehicles;
	}
	
	public boolean doVehicleExists(String vehicleId, String parkingId) {
		for (Vehicle vehicle : vehicles) {
			if (vehicle.matches(vehicleId, parkingId)) {
				return true;
			}
		}

		return false;
	}

	public void addVehicle(Vehicle vehicle) {
		vehicles.add(vehicle);
	}
}
