package com.company.property.vehicle;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import com.company.utility.IdGenerator;

public class Vehicle {
	private static final IdGenerator idGenerator = new IdGenerator("VEHICLE");

	private String vehicleId;
	private String gpsTrackerId;
	private String parkingPlace;
	private String parkingId;
	private VehicleDescription description;

	public Vehicle(String gpsTrackerId, String parkingPlace, String parkingId, VehicleDescription description) {
		this.vehicleId = idGenerator.generateId();
		this.gpsTrackerId = gpsTrackerId;
		this.parkingPlace = parkingPlace;
		this.parkingId = parkingId;
		this.description = description;
	}

	public boolean matches(String producer, String parkingId, int minPrice, int maxPrice, int seats, float minVolume, float maxVolume) {
		return this.parkingId.equals(parkingId)
				&& this.description.getProducer().equals(producer)
				&& this.description.getSeatNumber() == seats
				&& this.description.getPrice() >= minPrice && this.description.getPrice() <= maxPrice
				&& this.description.getMaxVolume() >= minVolume && this.description.getMaxVolume() <= maxVolume;
	}
	
	public boolean matches(String vehicleId, String parkingId) {
		return this.vehicleId.equals(vehicleId)
				&& this.parkingId.equals(parkingId);
	}

	public String getVehicleId() {
		return vehicleId;
	}

	@Override
	public String toString() {
		return "ID : " + vehicleId + "\n"
				+ "PARKING : " + parkingId + " " + parkingPlace + "\n"
				+ description.toString();
	}
}
