package com.company.transaction;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import java.util.Date;

public class Booking extends Transaction {
	private String state;

	public Booking(String userId, String vehicleId, String parkingId, String state, Date bookStart, Date bookEnd) {
		super(userId, vehicleId, parkingId, bookStart, bookEnd);

		this.state = state;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}
}