package com.company.transaction;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import java.util.Date;

public class Booking extends Transaction {
	public static final String STATE_TAKEN = "stateTaken";
	public static final String STATE_RETURNED = "stateReturned";
	public static final String STATE_CASE = "stateCase";
	public static final String STATE_BOOKED = "stateBooked";

	private String state;

	public Booking(String userId, String vehicleId, String parkingId, Date bookStart, Date bookEnd, String state) {
		super(userId, vehicleId, parkingId, bookStart, bookEnd);

		this.state = state;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}
}