package com.company.transaction;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//




public class TransactionFactory {
	public void process(Object userId, Object vehicleId, Object parkingId, Object bookEnd, Object bookStart) {
	
	}
	
	public void process(Object transaction) {
	
	}
	
	public void processViolator(Object transaction) {
	
	}
	
	public void processViolator(Object transaction, Object comment) {
	
	}
}
