package com.company.transaction;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import com.company.transactionStrategy.TransactionChoiseStrategy;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TransactionCatalog {
	private List<Transaction> transactions;

	public TransactionCatalog() {
		this.transactions = new ArrayList<>();
	}

	public Transaction findTransaction(TransactionChoiseStrategy strategy) {
		for (Transaction transaction : transactions) {
			if (strategy.matches(transaction)) {
				return transaction;
			}
		}

		return null;
	}
	
	public void findTransactions(TransactionChoiseStrategy strategy) {
	
	}
	
	public void addBooking(String userId, String vehicleId, String parkingId, Date bookEnd, Date bookStart) {
		Booking booking = new Booking(userId, vehicleId, parkingId, bookStart, bookEnd, Booking.STATE_BOOKED);
		transactions.add(booking);
	}
	
	public void processTransaction(Transaction transaction) {
	
	}
}
