package com.company.transaction;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import com.company.transaction.TransactionCatalog;

public class TransactionController {
	private TransactionCatalog transactionCatalog;
	private TokenCatalog tokenCatalog;

	public void addBooking(Object userId, Object vehicleId, Object parkingId, Object bookEnd, Object bookStart) {
	
	}
	
	public void findTransaction(Object userId) {
	
	}
	
	public void findAndRemoveToken(Object tokenId, Object userId, Object targetId, Object targetType) {
	
	}
	
	public void completeTransaction(Object vehicleId) {
	
	}
	
	public void findAndReportViolators(Object date) {
	
	}
}
