package com.company.transaction;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import com.company.transactionStrategy.*;

import java.util.Date;

public class TransactionController {
	private TransactionCatalog transactionCatalog;
	private TokenCatalog tokenCatalog;

	public TransactionController() {
		transactionCatalog = new TransactionCatalog();
		tokenCatalog = new TokenCatalog();
	}

	public Token[] addBooking(String userId, String vehicleId, String parkingId, Date bookStart, Date bookEnd) {
		ExistChoiseStrategy existChoiseStrategy = new ExistChoiseStrategy();
		UserViolationChoiseSubStrategy violationChoiseSubStrategy = new UserViolationChoiseSubStrategy(userId, vehicleId);
		IntersectChoiseSubStrategy intersectChoiseSubStrategy = new IntersectChoiseSubStrategy(vehicleId, bookStart, bookEnd);

		existChoiseStrategy.add(violationChoiseSubStrategy);
		existChoiseStrategy.add(intersectChoiseSubStrategy);

		Transaction existingTransaction = transactionCatalog.findTransaction(existChoiseStrategy);

		if (existingTransaction != null) {
			return null;
		}

		transactionCatalog.addBooking(userId, vehicleId, parkingId, bookStart, bookEnd);

		Token[] tokens = new Token[2];
		tokens[0] = tokenCatalog.addToken(userId, parkingId, Token.TARGET_TYPE_MAIN_GATE);
		tokens[1] = tokenCatalog.addToken(userId, vehicleId, Token.TARGET_TYPE_VEHICLE);

		return tokens;
	}
	
	public Transaction findTransaction(String userId) {
		OwnerChoiseStrategy ownerChoiseStrategy = new OwnerChoiseStrategy(userId);

		return transactionCatalog.findTransaction(ownerChoiseStrategy);
	}

	public Transaction findActiveTransaction(String vehicleId) {
		VehicleStrategy vehicleStrategy = new VehicleStrategy(vehicleId);

		return transactionCatalog.findTransaction(vehicleStrategy);
	}


	public boolean doTokenExists(String tokenId, String userId, String targetId, String targetType) {
		return tokenCatalog.doTokenExists(tokenId, userId, targetId, targetType);
	}

	public void removeToken(String tokenId, String userId, String targetId, String targetType) {
		tokenCatalog.remove(tokenId, userId, targetId, targetType);
	}
	
	public Transaction findAndProcessViolator(Date date) {
		DateViolationChoiseStrategy dateViolationChoiseStrategy = new DateViolationChoiseStrategy(date);

		Transaction transaction = transactionCatalog.findTransaction(dateViolationChoiseStrategy);

		if (transaction == null) {
			return null;
		}

		transactionCatalog.processViolation(transaction);

		return transaction;
	}

	public void processTransaction(Transaction transaction, String notes) {
		transactionCatalog.processTransaction(transaction, notes);
	}

	public Token makeToken(Transaction transaction, String targetType) {
		String targetId = null;

		if (targetType.equals(Token.TARGET_TYPE_MAIN_GATE) || targetType.equals(Token.TARGET_TYPE_SECOND_GATE)) {
			targetId = transaction.getParkingId();
		} else if (targetType.equals(Token.TARGET_TYPE_VEHICLE)) {
			targetId = transaction.getVehicleId();
		}

		return tokenCatalog.addToken(transaction.getUserId(), targetId, targetType);
	}
}
