package com.company.transaction;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import java.util.Date;

public class TransactionFactory {
	private static TransactionFactory sharedFactory;

	private TransactionFactory() {

	}

	public static TransactionFactory sharedFactory() {
		if (sharedFactory == null) {
			sharedFactory = new TransactionFactory();
		}

		return sharedFactory;
	}

	public Transaction process(String userId, String vehicleId, String parkingId, Date bookStart, Date bookEnd) {
		return new Booking(userId, vehicleId, parkingId, bookStart, bookEnd);
	}
	
	public void process(Object transaction) {
	
	}
	
	public void processViolator(Object transaction) {
	
	}
	
	public void processViolator(Object transaction, Object comment) {
	
	}
}
