package com.company.transaction;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import java.util.Date;

public class Transaction {
	private String userId;
	private Date bookStart;
	private Date bookEnd;
	private String vehicleId;
	private String parkingId;

	public Transaction(String userId, String vehicleId, String parkingId, Date bookStart, Date bookEnd) {
		this.userId = userId;
		this.vehicleId = vehicleId;
		this.parkingId = parkingId;
		this.bookStart = bookStart;
		this.bookEnd = bookEnd;
	}

	public String getUserId() {
		return userId;
	}

	public String getVehicleId() {
		return vehicleId;
	}

	public String getParkingId() {
		return parkingId;
	}

	public Date getBookStart() {
		return bookStart;
	}

	public Date getBookEnd() {
		return bookEnd;
	}
}