package com.company.transactionStrategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import com.company.transaction.Transaction;

import java.util.Date;

public class DateViolationChoiseStrategy implements TransactionChoiseStrategy {
	private Date violationDate;

	public DateViolationChoiseStrategy(Date violationDate) {
		this.violationDate = violationDate;
	}

	@Override
	public boolean matches(Transaction transaction) {
		return transaction.getBookEnd().before(violationDate);
	}
}
