package com.company.transactionStrategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import com.company.transaction.Transaction;

public interface TransactionChoiseSubStrategy extends TransactionChoiseStrategy {
	@Override
	public boolean matches(Transaction transaction);
}
