package com.company.transactionStrategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import com.company.transaction.Booking;
import com.company.transaction.Processed;
import com.company.transaction.Transaction;
import com.company.transaction.TransactionFactory;

public class UserViolationChoiseSubStrategy implements TransactionChoiseSubStrategy {
	private String userId;
	private String vehicleId;

	public UserViolationChoiseSubStrategy(String userId, String vehicleId) {

	}

	@Override
	public boolean matches(Transaction transaction) {
		if (transaction instanceof Booking) {
			Booking booking = (Booking) transaction;

			return (booking.getVehicleId().equals(vehicleId) && booking.getState().equals(TransactionFactory.STATE_CASE))
					|| (booking.getUserId().equals(userId) && !booking.getState().equals(TransactionFactory.STATE_RETURNED));
		} else if (transaction instanceof Processed) {
			Processed processed = (Processed) transaction;

			return processed.getUserId().equals(userId) && processed.getSystemFeedbackStatus().equals(TransactionFactory.STATUS_BAD);
		}

		return true;
	}
}