package com.company.transactionStrategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import com.company.transaction.Booking;
import com.company.transaction.Transaction;
import com.company.transaction.TransactionFactory;

public class VehicleStrategy implements TransactionChoiseStrategy {
	private String vehicleId;

	public VehicleStrategy(String vehicleId) {
		this.vehicleId = vehicleId;
	}

	@Override
	public boolean matches(Transaction transaction) {
		if (transaction instanceof Booking) {
			Booking booking = (Booking) transaction;
			return booking.getVehicleId().equals(vehicleId) && (booking.getState().equals(TransactionFactory.STATE_TAKEN) || booking.getState().equals(TransactionFactory.STATE_CASE));
		}

		return false;
	}
}
