package com.company.transactionStrategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @com.company.vehicle.Vehicle com.company.transaction.Booking
//  @ Author : @Nick Sargsyan, Anna Vardanyan
//
//


import com.company.transaction.Transaction;

public class VehicleStrategy implements TransactionChoiseStrategy {
	private String vehicleId;

	public VehicleStrategy(String vehicleId) {
		this.vehicleId = vehicleId;
	}

	@Override
	public boolean matches(Transaction transaction) {
		return true;
	}
}
